/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linter;

import java.io.File;
import java.io.IOException;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.Scanner;

public class App {

    public static void main(String[] args) {

        Path path = Paths.get("./app/src/main/resources/gates.js");
        System.out.println(linter(path.toString()));
    }

    public static String linter(String filePath) {

        String printLine = "";
        try {

            File myPath = new File(filePath);
            Scanner lineReader = new Scanner(myPath);
            int counter = 1;
            while (lineReader.hasNextLine()) {
                String line = lineReader.nextLine();
                if (!line.endsWith(";") && !line.endsWith("}") && !line.endsWith("{") && !line.contains("else") && !line.contains("if") && !line.isEmpty() || line.contains("return") && !line.endsWith(";")) {

                    printLine = printLine + "Line " + counter + " : Missing semicolon.\n";

                }
                counter++;
            }
            lineReader.close();
        } catch (IOException ioException) {
            System.out.println(ioException.getMessage());
        }
        return printLine;
    }
}
